apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: dapr-keyvault
  #  kubectl create secret generic keyvaulttenantid --from-literal=keyVaultTenantId=<TENANT-ID>
  - name: spnTenantId
    secretKeyRef:
      name: keyvaulttenantid #lowercase required for kubernetes
      key: keyVaultTenantId
  #  kubectl create secret generic keyvaultclientid --from-literal=keyvaultClientId=<CLIENT-ID>
  - name: spnClientId    
    secretKeyRef:
      name: keyvaultclientid #lowercase required for kubernetes
      key: keyVaultClientId
  # - name: spnCertificateFile
  #   value : "C:\\Users\\jguerrerominero\\dapr-keyvault.pfx"
  # Run from command line: 'kubectl create secret generic key-valut-cert --from-file=C:\Users\jguerrerominero\dapr-keyvault.pfx'
  - name: spnCertificate
    secretKeyRef:
      name: key-vault-cert
      key: dapr-keyvault.pfx
  - name: tableStorageKey
    secretRef: tableStorageKey
  
auth:
  secretStore: kubernetes