apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bindingeventdemo
  namespace: default
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: "daprbindings"
  - name: storageAccessKey
    value: "O2JkBFMa8DJ+bA08PqjMzdqLtdXQLaNdCl4zyBko06kQJasbNXwLa7SJoTJq9vCQ5oi+5OWda1MItGAxRNXEJA=="
  - name: queue
    value: "queuedemo1"
  - name: ttlInSeconds
    value: "60"
