apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    value: "daprdemo1" # <- Update according to Azure Storage Account name
  - name: accountKey
    value: voDntVRSl1k63qeK98wII9Pj4u7vi4pW3R6a/iRdeUDdUc/TCoUbmK971hey+cwnImscCcbwL73TIiE9YZdV4w==
  - name: tableName
    value: daprdemotable # <- Update according to Azure Storage table name, once you shoud be created previously