#
# Generated automatically using APIM menu optino: "Deployment and infrastructure" - "gateway"
# REF: https://docs.microsoft.com/en-us/azure/api-management/how-to-deploy-self-hosted-gateway-azure-kubernetes-service
#
# NOTE: Before deploying to a production environment, please review the documentation -> https://aka.ms/self-hosted-gateway-production
      # annotations:
      #   dapr.io/enabled: "true"
      #   dapr.io/app-id: "alltogether"    
      #   dapr.io/config: "tracing"    
      #   dapr.io/log-as-json: "true"
      #   dapr.io/log-level: "debug"      

# NOTE: Before deploying to a production environment, please review the documentation -> https://aka.ms/self-hosted-gateway-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: altogether-env
data:
  config.service.endpoint: "https://elguerre-apim.management.azure-api.net/subscriptions/599c98c2-aa8d-479a-940d-ee0d3f1e5d2e/resourceGroups/puck/providers/Microsoft.ApiManagement/service/elguerre-apim?api-version=2021-01-01-preview"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: altogether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: altogether
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: altogether
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "alltogether"    
        dapr.io/config: "tracing"    
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"            
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: altogether
        image: mcr.microsoft.com/azure-api-management/gateway:latest
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /internal-status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: altogether-token
              key: value
        envFrom:
        - configMapRef:
            name: altogether-env
---
apiVersion: v1
kind: Service
metadata:
  name: altogether
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: altogether