apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queuebinding
  namespace: default
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: "daprbindings"
  - name: storageAccessKey    
    secretKeyRef:
      name: queueStorageKey
      key: queueStorageKey
  - name: queue
    value: "queuedemo1"

auth:
  secretStore: secretstore