apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.azure.keyvault        
  version: v1
  metadata:
  - name: vaultName
    value: dapr-keyvault
  - name: spnTenantId
    value: "<YOUR-TENANT-ID>"
  - name: spnClientId
    value: "<YOUR-SPN-CLIENT-ID>"
  - name: spnCertificateFile
    value : "C:\\Users\\jguerrerominero\\dapr-keyvault.pfx"