apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    value: daprdemo1
  - name: accountKey
    secretKeyRef:
      name: azureStorageKey
      key:  azureStorageKey
  - name: tableName
    value: daprdemotable

auth:
  secretStore: secretstore