apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    value: daprdemo1
  - name: tableName
    value: daprdemotable    
  - name: accountKey    
    secretKeyRef:
      name: tableStorageKey
      key: tableStorageKey

auth:
  secretStore: secretstore